fix markdown links into github repo
FusionAuth/fusionauth-react-sdk pull request #19
Opened 2022-12-14 22:48 UTC by bhalsey

## What is this PR and why do we need it?

fix markdown links into github repo

2022-12-14 22:51 UTC, mooreds requested changes
I think we want these to be `main` not `master`. Other than that, looks great. Thanks!

2022-12-14 23:19 UTC, bhalsey commented
> I think we want these to be `main` not `master`. Other than that, looks great. Thanks!

Good catch, thanks.

2022-12-14 23:31 UTC, andrewpai approved these changes

2022-12-15 00:16 UTC, mooreds approved these changes
LGTM

2022-12-15 05:36 UTC, merged