fixes usage of `waitFor` to render component tests
FusionAuth/fusionauth-react-sdk pull request #84
Opened 2024-02-15 17:01 UTC by JakeLo123

## What is this PR and why do we need it?
Addressing issue #83. The component tests (buttons, and HOC tests) use waitFor to render components. This can cause unexpected behavior.

- removing uses of `AfterEach... jest.clearAllMocks()` in tests that don't use mocks.
- updating uses of `toBeCalled()` (deprecated) to `toHaveBeenCalled()`

#### Pre-Merge Checklist (if applicable)
-   [x] Unit and Feature tests have been added/updated for logic changes, or there is a justifiable reason for not doing so.

2024-02-16 18:57 UTC, BriDavidson requested changes
<img width="535" alt="Screenshot 2024-02-16 at 11 56 20 AM" src="https://github.com/FusionAuth/fusionauth-react-sdk/assets/58482016/55b01f28-3d66-4b1f-bdfc-da23e1c89ec5">
I am seeing that 8 tests are getting skipped on this branch however not. much specification as to which ones are being skipped or why. Is this expected behavior with these changes? All tests appear to run on main

2024-02-16 19:03 UTC, JakeLo123 commented
> I am seeing that 8 tests are getting skipped on this branch

that got fixed on [this PR](https://github.com/FusionAuth/fusionauth-react-sdk/pull/81), so it's not an effect of this branch.

2024-02-21 17:03 UTC, BriDavidson approved these changes

2024-02-21 20:58 UTC, dmackinn approved these changes

2024-02-22 19:50 UTC, merged